name: Build

on: [push]

jobs:
               
  build-macos:
    name: build-macos
    runs-on: macos-latest
    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        lfs: 'true'
        fetch-depth: 0
    - name: Get all tags
      run: |
        git show-ref --tags
        git log -40
        git describe
    - name: Export GitHub Actions cache environment variables for vcpkg
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    - name: Install CMake
      uses: lukka/get-cmake@latest
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
        
    - name: CMake configure, build vcpkg packages, build & test
      uses: lukka/run-cmake@v10
      with:
        configurePreset: mac-production
        buildPreset: mac-production
        testPreset: mac-production
        packagePreset: mac-production

    - name: Create installer
      shell: bash
      run: |
        cpack --preset mac-production
        ls -l build/package
    - name: On failure, Capture build folders as artifact
      if: ${{ failure() }}
      shell: bash
      run: |
        mkdir -p build vcpkg/buildtrees
        tar cfz build.tgz build
        tar cfz vcpkg-buildtrees.tgz vcpkg/buildtrees
        ls -l
    - name: On failure, Upload build folder
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: lldash-darwin-arm64-build-folder
        path: build.tgz
    - name: On failure, Upload vcpkg buildtrees folder
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: lldash-darwin-arm64-vcpkg-buildtrees-folder
        path: vcpkg-buildtrees.tgz
    - name: Upload installer folder
      uses: actions/upload-artifact@v4
      with:
        name: lldash-darwin-arm64-${{ github.ref_name }}.tar.gz
        path: build/package/lldash-darwin-arm64-*.tar.gz

               
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    env: 
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        lfs: 'true'
        fetch-depth: 0
    - name: Get all tags
      run: |
        git show-ref --tags
        git log -40
        git describe
    - name: Export GitHub Actions cache environment variables for vcpkg
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    - name: Install CMake
      uses: lukka/get-cmake@latest
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
        
    - name: CMake configure, build vcpkg packages, build & test
      uses: lukka/run-cmake@v10
      with:
        configurePreset: linux-production
        buildPreset: linux-production
        testPreset: linux-production
        packagePreset: linux-production

    - name: Create installer
      shell: bash
      run: |
        cpack --preset linux-production
        ls -l build/package
    - name: On failure, Capture build folders as artifact
      if: ${{ failure() }}
      shell: bash
      run: |
        mkdir -p build vcpkg/buildtrees
        tar cfz build.tgz build
        tar cfz vcpkg-buildtrees.tgz vcpkg/buildtrees
        ls -l
    - name: On failure, Upload build folder
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: lldash-linux-x86_64-build-folder
        path: build.tgz
    - name: On failure, Upload vcpkg buildtrees folder
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: lldash-linux-x86_64-vcpkg-buildtrees-folder
        path: vcpkg-buildtrees.tgz
    - name: Upload installer folder
      uses: actions/upload-artifact@v4
      with:
        name: lldash-linux-x86_64-${{ github.ref_name }}.tar.gz
        path: build/package/lldash-linux-x86_64-*.tar.gz
      
        
  build-linux-old:
    if: ${{ false }}
    name: build-linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        lfs: 'true'
        fetch-depth: 0
    - name: Get all tags
      run: |
        git show-ref --tags
        git log -40
        git describe
    - name: Export GitHub Actions cache environment variables for vcpkg
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    - name: Install build-time dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm
        sudo apt-get install -y libltdl-dev
    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ github.workspace }}/build
        configure-options: --preset linux-production -Wno-dev 
        build-options: --preset linux-production
        run-test: true
        install-build: true
        install-options: --prefix ${{ github.workspace }}/installed
      env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: Create installer
      shell: bash
      run: |
        cpack --preset linux-production
        ls -l build/package
    - name: On failure, Capture build folders as artifact
      if: ${{ failure() }}
      shell: bash
      run: |
        mkdir -p build vcpkg/buildtrees
        tar cfz build.tgz build
        tar cfz vcpkg-buildtrees.tgz vcpkg/buildtrees
        ls -l
    - name: On failure, Upload build folder
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: lldash-linux-x86_64-build-folder
        path: build.tgz
    - name: On failure, Upload vcpkg buildtrees folder
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: lldash-linux-x86_64-vcpkg-buildtrees-folder
        path: vcpkg-buildtrees.tgz
    - name: Upload installer folder
      uses: actions/upload-artifact@v4
      with:
        name: lldash-linux-x86_64-${{ github.ref_name }}.tar.gz
        path: build/package/lldash-linux-x86_64-*.tar.gz
