name: Build and Test

on:
  push:
    branches:
      - master
      - 104-cwipc-v80
    tags:
      - v*
      - exp*
  pull_request:
    branches:
      - master
permissions:
  packages: write
env:
  USERNAME: MotionSpell
  VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg
  FEED_URL: https://nuget.pkg.github.com/MotionSpell/index.json
  VCPKG_BINARY_SOURCES: clear;nuget,https://nuget.pkg.github.com/MotionSpell/index.json,readwrite
  TESTLATENCY_ARGS: --uncompressed --npoints 4000 --duration 30 --fps 5 --seg_dur 2000 --print-latencies
# The following environment variables can be set to run the tests in verbose or debug mode.
# Only use to find issues that show up in Github Actions but not on developer machines.
  TESTLATENCY_VERBOSE:
#  TESTLATENCY_VERBOSE: --verbose
#  TESTLATENCY_VERBOSE: --verbose --debug
#  LLDASH_LOGGING: 1
          
jobs:
  linux-intel-build:
    runs-on: ubuntu-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux-dynamic

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0  
    
    - name: Set up environment variables
      run: |
        echo "SIGNALS_REPO=https://github.com/MotionSpell/signals.git" >> $GITHUB_ENV
        echo "BUILD_DIR=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Bootstrap vcpkg
      shell: bash
      run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

    - name: Install mono for vcpkg
      shell: bash
      run: sudo apt install mono-complete

    - name: Add NuGet Sources for vcpkg
      shell: bash
      run: |
        mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
          sources add \
          -Source "${{ env.FEED_URL }}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{ env.USERNAME }}" \
          -Password "${{ github.token }}"
        mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
          setapikey "${{ github.token }}" \
          -Source "${{ env.FEED_URL }}"

    - name: Install dependencies with install_debian_prerequisites.sh script
      run: scripts/install_debian_prerequisites.sh

    - name: Fix for libcrypto build
      run: |
        sudo apt-get update && \
              sudo apt-get autoremove -y libtool && \
              sudo apt-get install -y libtool && \
              libtoolize --copy --force

    - name: Install CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.31.1"
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
        
    - name: CMake configure, build vcpkg packages, build & test
      uses: lukka/run-cmake@v10
      with:
        configurePreset: linux-production
        buildPreset: linux-production
        testPreset: linux-production
        packagePreset: linux-production

    - name: Upload vcpkg buildtrees in case of failure
      if: ${{ failure() }} 
      uses: actions/upload-artifact@v4
      with:
        name: linux-intel-buildtrees
        path: ./vcpkg/buildtrees
        retention-days: 5
    
    - name: Upload cmake build folder in case of failure
      if: ${{ failure() }} 
      uses: actions/upload-artifact@v4
      with:
        name: linux-intel-build-folder
        path: ./build
        retention-days: 5

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: lldash-linux-x86_64
        path: build/package/lldash-*.tar.gz

  linux-intel-test:
    runs-on: ubuntu-latest
    needs:
      - linux-intel-build
    steps:
    - name: Download intel linux package
      uses: actions/download-artifact@v4
      with:
        name: lldash-linux-x86_64
        path: ${{ github.workspace }}

    - name: Install lldash
      shell: bash
      run: |
        tar xfv lldash-linux-*.tar.gz
        mv lldash-linux-*/ installed
        ls -l

    - name: Install cwipc and other pipeline test dependencies
      run: |
        cmake --install build
        source tests/setup_test_environment.sh
        cwipc_view --version
        
    - name: Run integration tests
      timeout-minutes: 2
      run: |
        source .venv/bin/activate
        python tests/testlatency/testlatency.py ${{ env.TESTLATENCY_VERBOSE }} ${{ env.TESTLATENCY_ARGS }} --logdir logs
    
    - name: Upload all logs
      if: always()  # for debug purposes  
      uses: actions/upload-artifact@v4
      with:
        name: linux-test-logs
        path: ${{ env.BUILD_DIR }}/logs/**/*
        retention-days: 5

  macos-arm64-build:
    runs-on: macos-latest
    env:
      VCPKG_DEFAULT_TRIPLET: arm64-osx-dynamic

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set up environment variables
      run: |
        echo "BUILD_DIR=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Bootstrap vcpkg
      shell: bash
      run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

    - name: Install nuget and mono for vcpkg
      shell: bash
      run: brew install mono nuget

    - name: Add NuGet Sources for vcpkg
      shell: bash
      run: |
        mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
          sources add \
          -Source "${{ env.FEED_URL }}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{ env.USERNAME }}" \
          -Password "${{ github.token }}"
        mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
          setapikey "${{ github.token }}" \
          -Source "${{ env.FEED_URL }}"
  
    - name: Install dependencies with install_homebrew_prerequisites.sh script
      run: scripts/install_homebrew_prerequisites.sh

    - name: Install CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.31.1"
    
    - name: Setup vcpkg
      if: false # Testing if nuget caching works when vcpkg is executed by cmake.
      uses: lukka/run-vcpkg@v11
        
    - name: CMake configure, build vcpkg packages, build & test
      uses: lukka/run-cmake@v10
      with:
        configurePreset: mac-production
        buildPreset: mac-production
        testPreset: mac-production
        packagePreset: mac-production

    - name: Upload vcpkg buildtrees in case of failure
      if: ${{ failure() }} 
      uses: actions/upload-artifact@v4
      with:
        name: macos-vcpkg-buildtrees
        path: ./vcpkg/buildtrees
        retention-days: 5
    
    - name: Upload cmake build folder in case of failure
      if: ${{ failure() }} 
      uses: actions/upload-artifact@v4
      with:
        name: macos-build-folder
        path: ./build
        retention-days: 5

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: lldash-mac-arm64
        path: build/package/lldash-*.tar.gz

  macos-arm64-test:
    runs-on: macos-latest
    needs:
      - macos-arm64-build
    steps:
    - name: Download arm64 mac package
      uses: actions/download-artifact@v4
      with:
        name: lldash-mac-arm64
        path: ${{ github.workspace }}

    - name: Install lldash
      shell: bash
      run: |
        tar xfv lldash-darwin-*.tar.gz
        mv lldash-darwin-*/ installed
        ls -l

    - name: Install cwipc and other pipeline test dependencies
      run: |
        cmake --install build
        brew install python@3.12
        source tests/setup_test_environment.sh
        cwipc_view --version

    - name: Run integration tests
      timeout-minutes: 2
      run: |
        source .venv/bin/activate
        python tests/testlatency/testlatency.py ${{ env.TESTLATENCY_VERBOSE }} ${{ env.TESTLATENCY_ARGS }} --logdir logs

    - name: Upload all logs
      if: always()  # Upload logs even if the test fails for debug purposes
      uses: actions/upload-artifact@v4
      with:
        name: mac-arm64-test-logs
        path: ${{ env.BUILD_DIR }}/logs/**/*
        retention-days: 5

  macos-intel-build:
    runs-on: macos-15-intel
    env:
      VCPKG_DEFAULT_TRIPLET: x64-osx-dynamic

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set up environment variables
      run: |
        echo "BUILD_DIR=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Install mono for vcpkg
      shell: bash
      run: brew install mono

    - name: Bootstrap vcpkg
      shell: bash
      run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

    - name: Add NuGet Sources for vcpkg
      shell: bash
      run: |
        mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
          sources add \
          -Source "${{ env.FEED_URL }}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{ env.USERNAME }}" \
          -Password "${{ github.token }}"
        mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
          setapikey "${{ github.token }}" \
          -Source "${{ env.FEED_URL }}"

    - name: Install dependencies with install_homebrew_prerequisites.sh script
      run: scripts/install_homebrew_prerequisites.sh

    - name: Install CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.31.1"
    
    - name: Setup vcpkg
      if: false # Testing if nuget caching works when vcpkg is executed by cmake.
      uses: lukka/run-vcpkg@v11
        
    - name: CMake configure, build vcpkg packages, build & test
      uses: lukka/run-cmake@v10
      with:
        configurePreset: intelmac-production
        buildPreset: intelmac-production
        testPreset: intelmac-production
        packagePreset: intelmac-production

    - name: Upload vcpkg buildtrees in case of failure
      if: ${{ failure() }} 
      uses: actions/upload-artifact@v4
      with:
        name: macos-intel-vcpkg-buildtrees
        path: ./vcpkg/buildtrees
        retention-days: 5

    - name: Upload cmake build folder in case of failure
      if: ${{ failure() }} 
      uses: actions/upload-artifact@v4
      with:
        name: macos-intel-build-folder
        path: ./build
        retention-days: 5

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: lldash-mac-x86_64
        path: build/package/lldash-*.tar.gz

  macos-intel-test:
    runs-on: macos-15-intel
    needs:
      - macos-intel-build
    steps:
    - name: Download intel mac package
      uses: actions/download-artifact@v4
      with:
        name: lldash-mac-x86_64
        path: ${{ github.workspace }}

    - name: Install lldash
      shell: bash
      run: |
        tar xfv lldash-darwin-*.tar.gz
        mv lldash-darwin-*/ installed
        ls -l
    - name: Install cwipc and other pipeline test dependencies
      run: |
        cmake --install build
        brew install python@3.12 || true
        source tests/setup_test_environment.sh
        cwipc_view --version

    - name: Run integration tests
      timeout-minutes: 2
      run: |
        source .venv/bin/activate
        python tests/testlatency/testlatency.py ${{ env.TESTLATENCY_VERBOSE }} ${{ env.TESTLATENCY_ARGS }} --logdir logs


    - name: Upload all logs
      if: always()  # Upload logs even if the test fails for debug purposes
      uses: actions/upload-artifact@v4
      with:
        name: intelmac-test-logs
        path: ${{ env.BUILD_DIR }}/logs/**/*
        retention-days: 5

  macos-universal-build:
    runs-on: macos-latest
    needs:
      - macos-arm64-build
      - macos-intel-build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Get lipomerge
      run:
        git clone https://github.com/faaxm/lipomerge
    - name: Create download directory and upload directory
      run: |
        mkdir -p ${{ github.workspace }}/Assets
        mkdir -p ${{ github.workspace }}/tmp

    - name: Download MacOS Arm64 package
      uses: actions/download-artifact@v4
      with:
        name: lldash-mac-arm64
        path: ${{ github.workspace }}/tmp
    - name: Download MacOS Intel package
      uses: actions/download-artifact@v4
      with:
        name: lldash-mac-x86_64
        path: ${{ github.workspace }}/tmp
    - name: Create universal binary tree
      run: |
        set -x
        tar xfv ${{ github.workspace }}/tmp/*arm64*.tar.gz
        tar xfv ${{ github.workspace }}/tmp/*x86_64*.tar.gz
        
        pwd
        ls -l
        ls -l lipomerge

        dir_arm64=$(echo *arm64*)
        dir_x86_64=$(echo *x86_64*)
        dir_universal=${dir_arm64/arm64/universal}
        python3 lipomerge/lipomerge.py ${dir_arm64} ${dir_x86_64} ${dir_universal}
        echo "Universal directory: $dir_universal"
        tar cfz ${{ github.workspace }}/Assets/${dir_universal}.tar.gz ${dir_universal}

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: lldash-mac-universal
        path: ${{ github.workspace }}/Assets/lldash-*.tar.gz
  
  windows-intel-build:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-mingw-dynamic

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
        fetch-tags: true

    - name: Get all tags
      shell: bash
      run: |
        git show-ref --tags
        git log -10
        git describe

    - name: Install correct Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set up environment variables
      run: |
        echo "BUILD_DIR=$env:GITHUB_WORKSPACE" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Bootstrap vcpkg
      shell: pwsh
      run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat

    - name: Add NuGet sources for vcpkg
      shell: pwsh
      run: |
        ${{ env.VCPKG_EXE }} fetch nuget
        .$(${{ env.VCPKG_EXE }} fetch nuget) `
          sources add `
          -Source "${{ env.FEED_URL }}" `
          -StorePasswordInClearText `
          -Name GitHubPackages `
          -UserName "${{ env.USERNAME }}" `
          -Password "${{ github.token }}"
        .$(${{ env.VCPKG_EXE }} fetch nuget) `
          setapikey "${{ github.token }}" `
          -Source "${{ env.FEED_URL }}"


    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      id: msys2
      with:
        msystem: MINGW64
        path-type: inherit
      
    - name: Update msys2 using our install_mingw64_prerequisites script
      shell: msys2 {0}
      run: scripts/install_mingw64_prerequisites.sh
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
        
    - name: manually run CMake configure, build vcpkg packages, build & test
      shell: msys2 {0}
      env:
        MSYS2_PATH_TYPE: inherit
      run: |
        which cmake
        which make
        which mingw32-make
        cmake --version
        make --version
        mingw32-make --version
        ./scripts/buildpackage.sh mingw-production

    - name: Upload vcpkg buildtrees in case of failure
      if: ${{ failure() }} 
      uses: actions/upload-artifact@v4
      with:
        name: windows-vcpkg-buildtrees
        path: ./vcpkg/buildtrees
        retention-days: 5

    - name: Upload cmake build folder in case of failure
      if: ${{ failure() }} 
      uses: actions/upload-artifact@v4
      with:
        name: windows-intel-build-folder
        path: ./build
        retention-days: 5

    - name: Create package
      run: cpack --preset mingw-production

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: lldash-windows-x86_64
        path: build/package/lldash-*.tar.gz
  
  windows-intel-test:
    runs-on: windows-latest
    needs:
      - windows-intel-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Install correct Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Download Windows package
        uses: actions/download-artifact@v4
        with:
          name: lldash-windows-x86_64
          path: ${{ github.workspace }}

      - name: Install lldash
        shell: bash
        run: |
          tar xfv lldash-windows-*.tar.gz
          mv lldash-windows-*/ installed
          ls -l

      - name: Install cwipc and other pipeline test dependencies
        shell: pwsh
        run: |
          python --version
          & tests\setup_test_environment.ps1
          python --version
          pip freeze
          cwipc_view --version

      - name: Run integration tests
        timeout-minutes: 2
        shell: pwsh
        env: 
          CWIPC_LOGGING: DEBUG
        run: |
            & .\.venv\Scripts\Activate.ps1
            python tests/testlatency/testlatency.py ${{ env.TESTLATENCY_VERBOSE }} ${{ env.TESTLATENCY_ARGS }} --debug


      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-intel-test-logs
          path: |
            ${{ env.BUILD_DIR }}/logs/**/*
            ${{ env.BUILD_DIR }}/logs/*
          retention-days: 5

      - name: Upload test venv folder in case of failure
        if: ${{ failure() }} 
        uses: actions/upload-artifact@v4
        with:
          name: windows-intel-test-venv-folder
          path: ${{ env.BUILD_DIR }}/.venv/
          include-hidden-files: true
          retention-days: 5

      - name: Upload test installed folder in case of failure
        if: ${{ failure() }} 
        uses: actions/upload-artifact@v4
        with:
          name: windows-intel-test-installed-folder
          path: ./installed
          retention-days: 5
      
    
  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - linux-intel-build
      - macos-arm64-build
      - macos-intel-build
      - macos-universal-build
      - windows-intel-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Create Assets folder
        run: mkdir -p ${{ github.workspace }}/Assets
      - name: Download Linux package
        uses: actions/download-artifact@v4
        with:
          name: lldash-linux-x86_64
          path: ${{ github.workspace }}/Assets
      - name: Download MacOS Arm64 package
        uses: actions/download-artifact@v4
        with:
          name: lldash-mac-arm64
          path: ${{ github.workspace }}/Assets
      - name: Download MacOS Intel package
        uses: actions/download-artifact@v4
        with:
          name: lldash-mac-x86_64
          path: ${{ github.workspace }}/Assets
      - name: Download MacOS Intel package
        uses: actions/download-artifact@v4
        with:
          name: lldash-mac-universal
          path: ${{ github.workspace }}/Assets
      - name: Download Windows package
        uses: actions/download-artifact@v4
        with:
          name: lldash-windows-x86_64
          path: ${{ github.workspace }}/Assets
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/Assets/*
          body: |
            Release for ${{ github.ref }}
          generate_release_notes: true
          draft: true
          prerelease: true
