name: Build

on: [push]

jobs:
               
  build-macos:
    name: build-macos
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        lfs: 'true'
        fetch-depth: 0
    - name: Get all tags
      run: |
        git show-ref --tags
        git log -40
        git describe
    - name: Export GitHub Actions cache environment variables for vcpkg
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ github.workspace }}/build
        configure-options: --preset mac-production -Wno-dev 
        build-options: --preset mac-production
        run-test: true
        install-build: true
        install-options: --prefix ${{ github.workspace }}/installed
      env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: Create installer
      shell: bash
      run: |
        cpack --preset mac-production
        ls -l build/package
    - name: On failure, Capture build folders as artifact
      if: ${{ failure() }}
      shell: bash
      run: |
        mkdir -p build vcpkg/buildtrees
        tar cfz build.tgz build
        tar cfz vcpkg-buildtrees.tgz vcpkg/buildtrees
        ls -l
    - name: On failure, Upload build folder
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: lldash-darwin-arm64-build-folder
        path: build.tgz
    - name: On failure, Upload vcpkg buildtrees folder
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: lldash-darwin-arm64-vcpkg-buildtrees-folder
        path: vcpkg-buildtrees.tgz
    - name: Upload installer folder
      uses: actions/upload-artifact@v4
      with:
        name: lldash-darwin-arm64-${{ github.ref_name }}.tar.gz
        path: build/package/lldash-darwin-arm64-*.tar.gz
